spring:
<<<<<<< HEAD
  profiles:
    include:
      - naver
      - gmail
      - etc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abcd?serverTimezone=Asia/Seoul
    username: root
    password: '@tnqh258'
    data: data.sql
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create
    show-sql: true
    properties.hibernate.format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  port: 8080
=======
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    data: data.sql
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
>>>>>>> clover
