
insert into user (`id`,`email`,`nickname`,`password`) values(1,'kws3363@gmail.com','김수보','1234');
insert into user (`id`,`email`,`nickname`,`password`) values(2,'kws33623@gmail.com','김수2보','12334');
insert into user (`email`,`nickname`,`password`) value ('1@gasdf.com','a','dsfa');
insert into user (`email`,`nickname`,`password`) value ('2@gasdf.com','b','dsfa');
insert into user (`email`,`nickname`,`password`) value ('3@gasdf.com','c','dsfa');
insert into user (`email`,`nickname`,`password`) value ('4@gasdf.com','d','dsfa');
insert into user (`email`,`nickname`,`password`) value ('5@gasdf.com','e','dsfa');
insert into user (`email`,`nickname`,`password`) value ('6@gasdf.com','f','dsfa');
insert into user (`email`,`nickname`,`password`) value ('7@gasdf.com','g','dsfa');
insert into user (`email`,`nickname`,`password`) value ('8@gasdf.com','h','dsfa');
insert into user (`email`,`nickname`,`password`) value ('9@gasdf.com','i','dsfa');
insert into user (`email`,`nickname`,`password`) value ('10@gasdf.com','j','dsfa');
insert into user (`email`,`nickname`,`password`) value ('11@gasdf.com','k','dsfa');
insert into user (`email`,`nickname`,`password`) value ('12@gasdf.com','l','dsfa');
insert into user (`email`,`nickname`,`password`) value ('13@gasdf.com','m','dsfa');
insert into user (`email`,`nickname`,`password`) value ('14a@gasdf.com','n','dsfa');
insert into user (`email`,`nickname`,`password`) value ('15@gasdf.com','o','dsfa');
insert into user (`email`,`nickname`,`password`) value ('16@gasdf.com','p','dsfa');
insert into user (`email`,`nickname`,`password`) value ('17@gasdf.com','q','dsfa');
insert into user (`email`,`nickname`,`password`) value ('18a@gasdf.com','r','dsfa');
insert into user (`email`,`nickname`,`password`) value ('19@gasdf.com','s','dsfa');
insert into user (`email`,`nickname`,`password`) value ('20@gasdf.com','t','dsfa');
insert into user (`email`,`nickname`,`password`) value ('21@gasdf.com','u','dsfa');
insert into user (`email`,`nickname`,`password`) value ('22@gasdf.com','v','dsfa');
insert into user (`email`,`nickname`,`password`) value ('23@gasdf.com','w','dsfa');
insert into user (`email`,`nickname`,`password`) value ('24@gasdf.com','x','dsfa');
insert into user (`email`,`nickname`,`password`) value ('25@gasdf.com','y','dsfa');

insert into question(`id`,`title`,`user_id`) value('1','자바어려워요','1');
